# B4 Landscape Blank Template
# Paper size: B4 (257mm x 364mm)
# Orientation: Landscape
# Margins: 0.2cm (minimal)
# Cell size: 0.5cm x 0.5cm
# Printable area: ~44 rows x 58 columns per page
# Page breaks marked with borders at row 44 and column BF
